# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c

before_install:
- gem install cocoapods -v '>= 0.34.0'
- cd Example && pod install && cd -

script:
- xctool test -workspace Example/MLNetworkLogger.xcworkspace -scheme MLNetworkLogger -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
